### ISSUE TITLE
Unexpected Error encounted while declare my contract

### ISSUE THREAD

**Issue by Sayrarh** [software-mansion/protostar#1415]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `PROTOSTAR_VERSION`  |0.9.1                                                                                                                                          

| Cairo-lang | `CAIRO_LANG_VERSION` |0.10.3

| Git        | `GIT_VERSION`        |

## Current Behavior
I encounted this error while trying to declare my contract 

Unexpected Protostar error. Report it here:                       
https://github.com/software-mansion/protostar/issues

Traceback (most recent call last):
  File "binary_entrypoint.py", line 79, in <module>
  File "binary_entrypoint.py", line 23, in init
  File "protostar/start.py", line 21, in main
  File "protostar/start.py", line 47, in run_protostar
  File "protostar/start.py", line 42, in run_protostar
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "protostar/protostar_cli.py", line 80, in run
  File "protostar/protostar_cli.py", line 117, in _run_command_from_args
  File "protostar/argument_parser/cli_app.py", line 25, in run
  File "protostar/commands/declare_command.py", line 116, in run
  File "protostar/commands/declare_command.py", line 149, in declare
  File "protostar/starknet_gateway/gateway_facade.py", line 213, in declare
  File "starknet_py/net/account/account_client.py", line 406, in sign_declare_transaction
  File "starknet_py/net/account/account_client.py", line 329, in _get_max_fee
  File "starknet_py/net/account/account_client.py", line 514, in estimate_fee
  File "starknet_py/net/gateway_client.py", line 203, in estimate_fee
  File "starknet_py/net/http_client.py", line 70, in post
  File "starknet_py/net/http_client.py", line 37, in request
  File "starknet_py/net/http_client.py", line 51, in _make_request
  File "starknet_py/net/http_client.py", line 81, in handle_request_error
  File "starknet_py/net/http_client.py", line 115, in basic_error_handle
starknet_py.net.client_errors.ClientError: Client failed with code 500: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Requested contract address 0x1a2790b16d301149faf6f69d9a374e054109230b600e338ddf874cec53cb6f is not deployed."}
[132979] Failed to execute script 'binary_entrypoint' due to unhandled exception!

![Screenshot_20230125_173513](https://user-images.githubusercontent.com/95746919/214621924-ceda1309-7817-4154-b340-69b85e1707f1.png)

## Expected Behavior
The contract should successfully be declared so I can deploy the contract

## Steps to Reproduce

1.
2.
3.

**Comment by Arcticae** [comment]
It seems like your account is not deployed on the requested network
