### ISSUE TITLE
StarknetErrorCode.UNINITIALIZED_CONTRACT error when declaring contract with max-fee auto

### ISSUE THREAD

**Issue by Jrigada** [software-mansion/protostar#1432]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.9.1`  | 
| Cairo-lang | `0.10.3` | 
| Git        | `2.37.1`        | 

## Current Behavior

When declaring with protostar declare using an argent wallet, it throws the following error only when using `max-fee auto`. It works using `max-fee 1`

```
Traceback (most recent call last):
  File "binary_entrypoint.py", line 79, in <module>
  File "binary_entrypoint.py", line 23, in init
  File "protostar/start.py", line 21, in main
  File "protostar/start.py", line 47, in run_protostar
  File "protostar/start.py", line 42, in run_protostar
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "protostar/protostar_cli.py", line 80, in run
  File "protostar/protostar_cli.py", line 117, in _run_command_from_args
  File "protostar/argument_parser/cli_app.py", line 25, in run
  File "protostar/commands/declare_command.py", line 116, in run
  File "protostar/commands/declare_command.py", line 149, in declare
  File "protostar/starknet_gateway/gateway_facade.py", line 213, in declare
  File "starknet_py/net/account/account_client.py", line 406, in sign_declare_transaction
  File "starknet_py/net/account/account_client.py", line 329, in _get_max_fee
  File "starknet_py/net/account/account_client.py", line 514, in estimate_fee
  File "starknet_py/net/gateway_client.py", line 203, in estimate_fee
  File "starknet_py/net/http_client.py", line 70, in post
  File "starknet_py/net/http_client.py", line 37, in request
  File "starknet_py/net/http_client.py", line 51, in _make_request
  File "starknet_py/net/http_client.py", line 81, in handle_request_error
  File "starknet_py/net/http_client.py", line 115, in basic_error_handle
starknet_py.net.client_errors.ClientError: Client failed with code 500: {"code": "StarknetErrorCode.UNINITIALIZED_CONTRACT", "message": "Requested contract address 0x789cdffb54e65374563fa4e8733d461b46679209497f3a9f1916b9dcf025c4e is not deployed."}
[70403] Failed to execute script 'binary_entrypoint' due to unhandled exception!
```

## Expected Behavior

It should declare the contract and throw:
`Declare transaction was sent.`

## Steps to Reproduce

1. Create an ArgentX account, export the Private key and set it to the env variable of the protostar cli
2.
```
protostar declare ./build/main.json \
  --network testnet \
  --account ACCOUNT \
  --max-fee auto
```

**Comment by Arcticae** [comment]
Hi! Can you please tell me if `0x789cdffb54e65374563fa4e8733d461b46679209497f3a9f1916b9dcf025c4e` address from the error is your ArgentX account address?

**Comment by Jrigada** [comment]
It is!

**Comment by Arcticae** [comment]
@Jrigada seems like there is no account with that address on `testnet`, i checked both on starkscan & on voyager. Please make sure the account has been deployed correctly - this is not a protostar bug, i'm closing this issue.
