### ISSUE TITLE
Assertion Error. [39678] Failed to execute script 'binary_entrypoint' due to unhandled exception!

### ISSUE THREAD

**Issue by appetitoff** [software-mansion/protostar#1461]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.8.1`  |
| Cairo-lang | `0.10.1` |
| Git        | `2.39.1`        |
| Ubuntu       | `20.04.5 LTS`        |

## Current Behavior

Unexpected Protostar error. Report it here:
https://github.com/software-mansion/protostar/issues

Traceback (most recent call last):
  File "binary_entrypoint.py", line 80, in <module>
  File "binary_entrypoint.py", line 23, in init
  File "protostar/start.py", line 21, in main
  File "protostar/start.py", line 47, in run_protostar
  File "protostar/start.py", line 42, in run_protostar
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "protostar/protostar_cli.py", line 81, in run
  File "protostar/protostar_cli.py", line 125, in _run_command_from_args
  File "protostar/argument_parser/cli_app.py", line 25, in run
  File "protostar/commands/declare_command.py", line 110, in run
  File "protostar/cli/signable_command_util.py", line 77, in get_signer
  File "starknet_py/net/signer/stark_curve_signer.py", line 37, in from_private_key
  File "starkware/crypto/signature/signature.py", line 108, in private_to_stark_key
  File "starkware/crypto/signature/signature.py", line 103, in private_key_to_ec_point_on_stark_curve
AssertionError
[39678] Failed to execute script 'binary_entrypoint' due to unhandled exception!

## Expected Behavior

The smart contract has to be declared and I have to get a class hash for further deployment.

## Steps to Reproduce

Sequence of actions:
1.Created directory "NGT"
2. Went to it and use command "protostar init", specifying the directory "starknet_test"
3. Moved to the directory "starknet_test" and use command "protostar build" (The "build" directory is created)
4. Added ".env" file with private key of argentX wallet to mainnet (wallet is activated and has 0.0031ETH)
5. Trying to declare a smart contract with the command: "protostar declare ./build/main.json --account-address 0x0641DDD7177785a1eBDb17242b4dA700487644674fdca0b25BAD73d9607855E03 --max-fee auto --private-key-path ./.env --network mainnet"

**Comment by Arcticae** [comment]
@piotmag769 please also investigate this one when doing the one mentioned by Maks, assigning you for visibility

**Comment by piotmag769** [comment]
@appetitoff thanks for creating the issue!
Please double check if you have provided a valid private key as it may be an issue.
