### ISSUE TITLE
[8428] Failed to execute script 'binary_entrypoint' due to unhandled exception!

### ISSUE THREAD

**Issue by openluminus** [software-mansion/protostar#1463]
## Protostar version
| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | 0.9.1    |
| Cairo-lang | 0.10.3 |
| Git        | 2.39.0   |

## Current Behavior

When running the deploy command:
```bash
protostar deploy --network testnet
```

I'm getting an error stack:

```bash
$ protostar deploy --network testnet
Unexpected Protostar error. Report it here:                                                       
https://github.com/software-mansion/protostar/issues

Traceback (most recent call last):
  File "binary_entrypoint.py", line 79, in <module>
  File "binary_entrypoint.py", line 23, in init
  File "protostar/start.py", line 21, in main
  File "protostar/start.py", line 47, in run_protostar
  File "protostar/start.py", line 42, in run_protostar
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "protostar/protostar_cli.py", line 80, in run
  File "protostar/protostar_cli.py", line 117, in _run_command_from_args
  File "protostar/argument_parser/cli_app.py", line 25, in run
  File "protostar/commands/deploy_command.py", line 134, in run
  File "protostar/starknet_gateway/gateway_facade.py", line 134, in deploy_via_udc
  File "protostar/starknet_gateway/gateway_facade.py", line 89, in _create_udc_deployment
  File "starknet_py/net/udc_deployer/deployer.py", line 92, in create_deployment_call_raw
  File "starknet_py/common.py", line 31, in int_from_hex
TypeError: int() can't convert non-string with explicit base
[8428] Failed to execute script 'binary_entrypoint' due to unhandled exception!
```

## Expected Behavior

I don't know how the output should look like, but I guess receive the address of the deployed contract.

## Steps to Reproduce

1. Build the contracts with `protostar build`
2. Declare the contracts `protostar declare ./build/my_contract.json --network testnet --max-fee auto`
3. Deploy the contracts `protostar deploy --network testnet`

Here is a sample of my protostar.toml file:

```toml
[project]
protostar-version = "0.9.1"
lib-path = "lib"

[contracts]
main = ["src/main.cairo"]
my_contract = ["src/my_contract.cairo"]

[deploy]
account-address = 0xDEADBEEF_ my account address
private-key-path = "priv.key"
max-fee = "auto"

[declare]
account-address =0xDEADBEEF_ my account address
private-key-path = "priv.key"
max-fee = "auto"
```

**Comment by MaksymilianDemitraszek** [comment]
I think it my be related to #1461

**Comment by MaksymilianDemitraszek** [comment]
This also might be related https://github.com/software-mansion/protostar/issues/1445

**Comment by piotmag769** [comment]
@openluminus have you tried providing class hash while running deploy command?
Although it is not marked as required in [documentation](https://docs.swmansion.com/protostar/docs/cli-reference#deploy) I think it may be necessary.
