### ISSUE TITLE
Investigate if we can improve error message for cheatcodes

### ISSUE THREAD

**Issue by MaksymilianDemitraszek** [software-mansion/protostar#1664]
If we provide non existing contract in cheatcode then the result is
```
Collected 1 suite, and 1 test case (0.19)
[FAIL] tests/test_main.cairo test_declare_cairo0 (time=0.00s)
[error_messages]:
— Error at pc=0:5:
Got an exception while executing a hint.Traceback (most recent call last):
  File "<hint0>", line 1, in <module>
  File "protostar/cheatable_starknet/callable_hint_locals/callable_hint_local.py", line 43, in wrapper
  File "protostar/cheatable_starknet/callable_hint_locals/declare_cairo0_hint_local.py", line 42, in declare_cairo0
  File "protostar/compiler/project_compiler.py", line 101, in compile_contract_from_contract_identifier
  File "protostar/compiler/project_compiler.py", line 107, in compile_contract_from_contract_name
  File "protostar/configuration_file/configuration_file_v2.py", line 99, in get_contract_source_paths
protostar.configuration_file.configuration_file.ContractNameNotFoundException: Couldn't find `contractz` in `protostar.toml::[contracts]`
```
It would be better to not include the callstack data in the error.
This should be done by catching errors from starknet which can be caused by user and re-raise `CheatcodeException`

**Comment by MaksymilianDemitraszek** [comment]
Solved by this one
https://github.com/software-mansion/protostar/commit/032f32bf1fe9d481cde40849e33dbe973d679716
