### ISSUE TITLE
Contract call failed

### ISSUE THREAD

**Issue by unegare** [software-mansion/protostar#1712]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | 0.9.2   |
| Cairo-lang | 0.10.3 |
| Git        | `GIT_VERSION`        |

## Current Behavior

```
$ protostar call --contract-address 0x016d61017fc5188ea9bc21ba65cdff1b91c0d93d815485071ac4573b8ae1ec47 --function "get_balance" --network testnet
Unexpected Protostar error. Report it here:                                                                                             
https://github.com/software-mansion/protostar/issues

Traceback (most recent call last):
  File "binary_entrypoint.py", line 79, in <module>
  File "binary_entrypoint.py", line 23, in init
  File "protostar/start.py", line 21, in main
  File "protostar/start.py", line 47, in run_protostar
  File "protostar/start.py", line 42, in run_protostar
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "protostar/protostar_cli.py", line 80, in run
  File "protostar/protostar_cli.py", line 117, in _run_command_from_args
  File "protostar/argument_parser/cli_app.py", line 25, in run
  File "protostar/commands/call/call_command.py", line 67, in run
  File "protostar/commands/call/call_command.py", line 97, in call
  File "protostar/starknet_gateway/call/call_use_case.py", line 32, in execute
  File "protostar/starknet_gateway/data_transformer_policy.py", line 59, in transform_entrypoint_output_to_human_if_abi_found
  File "protostar/starknet_gateway/abi_resolver.py", line 32, in resolve
  File "protostar/starknet_gateway/abi_resolver.py", line 45, in _resolve
  File "starknet_py/proxy/contract_abi_resolver.py", line 85, in resolve
  File "starknet_py/proxy/contract_abi_resolver.py", line 94, in get_abi_for_address
  File "starknet_py/proxy/contract_abi_resolver.py", line 182, in _get_class_at
  File "starknet_py/net/gateway_client.py", line 307, in get_class_by_hash
  File "marshmallow/schema.py", line 722, in load
  File "marshmallow/schema.py", line 909, in _do_load
marshmallow.exceptions.ValidationError: {'entry_points_by_type': {'EXTERNAL': {0: {'offset': ['Invalid value provided for felt: 66.']}, 1: {'offset': ['Invalid value provided for felt: 99.']}}, 'CONSTRUCTOR': {0: {'offset': ['Invalid value provided for felt: 122.']}}}}
[55540] Failed to execute script 'binary_entrypoint' due to unhandled exception!
```

## Expected Behavior

call the function and print the result

## Steps to Reproduce

1. just make a call `protostar call --contract-address 0x016d61017fc5188ea9bc21ba65cdff1b91c0d93d815485071ac4573b8ae1ec47 --function "get_balance" --network testnet`

**Comment by ptisserand** [comment]
It seems to be related to https://github.com/eqlabs/pathfinder/pull/986
