### ISSUE TITLE
`update` error

### ISSUE THREAD

**Issue by piotmag769** [software-mansion/protostar#1723]
Steps to reproduce:
```console
$ protostar install https://github.com/OpenZeppelin/cairo-contracts
```

Add `cairo-path = ["lib/cairo-contracts/src"]` to `[project]` section of the `protostar.toml` as shown in [the tutorial](https://docs.swmansion.com/protostar/docs/tutorials/dependencies-management#adding-a-dependency).

```console
$ protostar update
```

21:57:53 [INFO] Running dependency update
21:57:53 [ERROR] Update command failed
Unexpected Protostar error. Report it here:
https://github.com/software-mansion/protostar/issues

Traceback (most recent call last):
  File "binary_entrypoint.py", line 79, in <module>
  File "binary_entrypoint.py", line 23, in init
  File "protostar/start.py", line 21, in main
  File "protostar/start.py", line 47, in run_protostar
  File "protostar/start.py", line 42, in run_protostar
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "protostar/protostar_cli.py", line 80, in run
  File "protostar/protostar_cli.py", line 117, in _run_command_from_args
  File "protostar/argument_parser/cli_app.py", line 25, in run
  File "protostar/commands/update/update_command.py", line 65, in run
  File "protostar/commands/update/update_command.py", line 60, in run
  File "protostar/commands/update/update_command.py", line 88, in update
  File "protostar/commands/update/update_package.py", line 18, in update_package
KeyError: '.DS_Store'
[14776] Failed to execute script 'binary_entrypoint' due to unhandled exception!

**Comment by MaksymilianDemitraszek** [comment]
git dependencies will be deprecated
