### ISSUE TITLE
Proxy resolver does not currently support Cairo1 ABIs Error

### ISSUE THREAD

**Issue by barretodavid** [software-mansion/protostar#2073]
When trying to use Protostar as a CLI to interact with the default Cairo 1 smart contract that Protostar creates when doing `protostar init --minimal project` [deployed to testnet](https://testnet.starkscan.co/contract/0x03c308e8ed89a258d1c5398d81d11fcc2b008b7dc4f7e74fe07d9768d95bb9ef#read-write-contract-sub-read), the "call" command fails with the error `Proxy resolver does not currently support Cairo1 ABIs.`

This is the executed command:
```
protostar call --contract-address 0x03c308e8ed89a258d1c5398d81d11fcc2b008b7dc4f7e74fe07d9768d95bb9ef --function "get_balance" --network testnet
```

## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.13.0`  |
| Cairo-lang | `0.11.1.1` |
| Git        | `2.39.2`        |

## Current Behavior

The CLI command returns the following error:
```
Unexpected Protostar error. Report it here:                                                                                  
https://github.com/software-mansion/protostar/issues

Traceback (most recent call last):
  File "binary_entrypoint.py", line 85, in <module>
  File "binary_entrypoint.py", line 24, in init
  File "protostar/start.py", line 21, in main
  File "protostar/start.py", line 47, in run_protostar
  File "protostar/start.py", line 42, in run_protostar
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "protostar/protostar_cli.py", line 80, in run
  File "protostar/protostar_cli.py", line 117, in _run_command_from_args
  File "protostar/argument_parser/cli_app.py", line 25, in run
  File "protostar/commands/call/call_command.py", line 67, in run
  File "protostar/commands/call/call_command.py", line 97, in call
  File "protostar/starknet_gateway/call/call_use_case.py", line 32, in execute
  File "protostar/starknet_gateway/data_transformer_policy.py", line 59, in transform_entrypoint_output_to_human_if_abi_found
  File "protostar/starknet_gateway/abi_resolver.py", line 32, in resolve
  File "protostar/starknet_gateway/abi_resolver.py", line 45, in _resolve
  File "starknet_py/proxy/contract_abi_resolver.py", line 85, in resolve
  File "starknet_py/proxy/contract_abi_resolver.py", line 98, in get_abi_for_address
starknet_py.proxy.contract_abi_resolver.UnsupportedAbiError: Proxy resolver does not currently support Cairo1 ABIs.
[20160] Failed to execute script 'binary_entrypoint' due to unhandled exception!
```

## Expected Behavior

The CLI command should return the default value 0 as the variable has not been set:
```
Call successful.
Response:
{
    "res": 0
}
```

## Steps to Reproduce

Try executing this command on a terminal
```
protostar call --contract-address 0x03c308e8ed89a258d1c5398d81d11fcc2b008b7dc4f7e74fe07d9768d95bb9ef --function "get_balance" --network testnet
```

OR

1. Create a new project using `protostar init --minimal project`
2. Declare and deploy the smart contract to testnet
4. Try to "call" the get_balance" function using the `protostar call` command

## Possible Solution

I don't know

**Comment by Cevedale** [comment]
There is an issue with the Protostar CLI when trying to interact with the default Cairo 1 smart contract. The error indicates that the Proxy resolver does not currently support Cairo1 ABIs.
Check the Protostar documentation and release notes for any information regarding support for Cairo1 ABIs. The issue might be a known limitation, and there could be instructions or workarounds provided in the documentation.
If there is no immediate solution, consider using an earlier version of Cairo-lang that might be compatible with the Proxy resolver. However, be cautious about potential side effects and ensure that this is a viable temporary workaround.
If Protostar CLI continues to pose challenges, consider alternative methods for interacting with the smart contract, such as using other CLI tools or interacting directly with the smart contract on the testnet.
