### ISSUE TITLE
Fix `SSLCertVerificationError`

### ISSUE THREAD

**Issue by kasperski95** [software-mansion/protostar#313]
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "binary_entrypoint.py", line 8, in <module>
  File "protostar/start.py", line 33, in main
  File "protostar/start.py", line 26, in main
  File "asyncio/runners.py", line 43, in run
  File "asyncio/base_events.py", line 587, in run_until_complete
  File "protostar/protostar_cli.py", line 131, in run
  File "protostar/cli/cli_app.py", line 28, in run
  File "protostar/commands/deploy/deploy_command.py", line 110, in run
  File "protostar/commands/deploy/deploy_command.py", line 144, in deploy
  File "protostar/commands/deploy/starkware/starknet_cli.py", line 73, in deploy
  File "starkware/starknet/services/api/gateway/gateway_client.py", line 19, in add_transaction
  File "services/external_api/base_client.py", line 116, in _send_request
  File "aiohttp/client.py", line 1138, in __aenter__
  File "aiohttp/client.py", line 536, in _request
  File "aiohttp/connector.py", line 542, in connect
  File "aiohttp/connector.py", line 907, in _create_connection
  File "aiohttp/connector.py", line 1206, in _create_direct_connection
  File "aiohttp/connector.py", line 1187, in _create_direct_connection
  File "aiohttp/connector.py", line 988, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host alpha4.starknet.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')]
[15985] Failed to execute script 'binary_entrypoint' due to unhandled exception!
```

```
11:46:32 [INFO] Looking for a new version ...
11:46:32 [INFO] Starting upgrade from version 0.2.0 to version 0.2.1
11:46:32 [INFO] Pulling latest binary, version: 0.2.1
11:46:32 [ERROR] Upgrade failed
11:46:32 [INFO] Rolling back to the version 0.2.0
11:46:32 [INFO] Cleaning up after installation
Unexpected Protostar error. Report it here:
https://github.com/software-mansion/protostar/issues

Traceback (most recent call last):
  File "urllib/request.py", line 1350, in do_open
  File "http/client.py", line 1281, in request
  File "http/client.py", line 1327, in _send_request
  File "http/client.py", line 1276, in endheaders
  File "http/client.py", line 1036, in _send_output
  File "http/client.py", line 976, in send
  File "http/client.py", line 1451, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "protostar.py", line 8, in <module>
  File "src/start.py", line 27, in main
  File "src/start.py", line 20, in main
  File "asyncio/runners.py", line 43, in run
  File "asyncio/base_events.py", line 587, in run_until_complete
  File "src/protostar_cli.py", line 95, in run
  File "src/cli/cli_app.py", line 28, in run
  File "src/commands/upgrade/upgrade_command.py", line 44, in run
  File "src/commands/upgrade/upgrade_command.py", line 51, in upgrade
  File "src/commands/upgrade/upgrade_command.py", line 98, in upgrade
  File "src/commands/upgrade/upgrade_command.py", line 104, in _handle_error
  File "src/commands/upgrade/upgrade_command.py", line 93, in upgrade
  File "src/commands/upgrade/upgrade_command.py", line 112, in _pull_tarball
  File "urllib/request.py", line 247, in urlretrieve
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 543, in _open
  File "urllib/request.py", line 503, in _call_chain
  File "urllib/request.py", line 1393, in https_open
  File "urllib/request.py", line 1352, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
[22735] Failed to execute script 'protostar' due to unhandled exception!
```

**Comment by kasperski95** [comment]
This one is tricky to solve. I'm leaving it for now.

**Comment by salsasteve** [comment]
Getting this as well when i run `protostar -p testnet deploy ./build/main.json` or `protostar deploy ./build/main.json --network alpha-goerli`
