### ISSUE TITLE
CI workflow test failing

### ISSUE THREAD

**Issue by ametel01** [software-mansion/protostar#545]
Using the following workflow: 
``` 
on: [push]

name: test

jobs:
  check:
    name: Protostar project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Protostar
        uses: sambarnes/protostar-toolchain@main

      - name: Run tests
        run: protostar test
```

returns the following error:

```
Run protostar test
[1867] Failed to execute script 'binary_entrypoint' due to unhandled exception!
Traceback (most recent call last):
Unexpected Protostar error. Report it here:
  File "binary_entrypoint.py", line 11, in <module>
https://github.com/software-mansion/protostar/issues
  File "protostar/start.py", line 32, in main

  File "protostar/start.py", line 27, in main
  File "asyncio/runners.py", line [4](https://github.com/ametel01/No-Game/runs/7574485480?check_suite_focus=true#step:4:5)3, in run
  File "asyncio/base_events.py", line [5](https://github.com/ametel01/No-Game/runs/7574485480?check_suite_focus=true#step:4:6)87, in run_until_complete
  File "protostar/protostar_cli.py", line 215, in run
  File "protostar/cli/cli_app.py", line 28, in run
  File "protostar/commands/test/test_command.py", line 120, in run
  File "protostar/commands/test/test_command.py", line 139, in test
  File "protostar/commands/test/test_command.py", line 187, in _build_include_paths
  File "protostar/utils/config/project.py", line 77, in get_include_paths
  File "protostar/commands/test/expected_event.py", line 1[6](https://github.com/ametel01/No-Game/runs/7574485480?check_suite_focus=true#step:4:7), in collect_immediate_subdirectories
AssertionError: lib/cairo_contracts_git/cairo_contracts/src is supposed to be a directory! 
```

**Comment by kasperski95** [comment]
It looks like you don't run `protostar install` before running tests.

**Comment by mkaput** [comment]
Hi @ametel01 did @kasperski95's suggestion fix the issue for you?

Closing this issue as for now.
