### ISSUE TITLE
[BUG] Fuzzing fails because of python's 'ulimit' on macos 12.2.1

### ISSUE THREAD

**Issue by JorikSchellekens** [software-mansion/protostar#590]
## Protostar version

| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | 0.3.0 |
| Cairo-lang | ^0.9.1 |
| Git        | 2.37.1       |

## Current Behavior

Fuzzing a test which doesn't satisfy `expect_revert` for the following condition causes too many files to be opened.

## Steps to Reproduce

1. run a fuzzer test on the following:
```
@external
func test_safe_cast_fuzz {
    range_check_ptr, bitwise_ptr: BitwiseBuiltin*
  } (val: felt):

  %{
      if (ids.val % 2 == 0 and ids.val > (2**125 - 1) * 2):
          expect_revert()
  %}

  return ()
end
```
## Possible Solution

I checked my laptop's ulimit which is set to unlimited so doesn't seem to be caused by the OS, might be python?

## Crash log

```
[UNEXPECTED_EXCEPTION] tests/lib/test_math_q64.cairo
Traceback (most recent call last):
  File "hypothesis/core.py", line 729, in _execute_once_for_engine
  File "hypothesis/core.py", line 667, in execute_once
  File "hypothesis/executors.py", line 47, in default_new_style_executor
  File "hypothesis/core.py", line 663, in run
  File "protostar/commands/test/environments/fuzz_test_execution_environment.py", line 240, in inner
  File "asyncio/events.py", line 762, in new_event_loop
  File "asyncio/events.py", line 660, in new_event_loop
  File "asyncio/unix_events.py", line 51, in __init__
  File "asyncio/selector_events.py", line 57, in __init__
  File "selectors.py", line 511, in __init__
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "protostar/commands/test/test_runner.py", line 96, in run_test_suite
  File "protostar/commands/test/test_runner.py", line 157, in _run_test_suite
  File "protostar/commands/test/environments/factory.py", line 36, in invoke_test_case
  File "protostar/commands/test/environments/fuzz_test_execution_environment.py", line 155, in invoke
  File "protostar/commands/test/environments/fuzz_test_execution_environment.py", line 222, in to_thread
  File "concurrent/futures/thread.py", line 57, in run
  File "protostar/commands/test/environments/fuzz_test_execution_environment.py", line 151, in test_thread
  File "protostar/commands/test/environments/fuzz_test_execution_environment.py", line 111, in test
  File "hypothesis/core.py", line 1246, in wrapped_test
  File "hypothesis/internal/conjecture/datatree.py", line 30, in inconsistent_generation
hypothesis.errors.Flaky: Inconsistent data generation! Data generation behaved differently between different runs. Is your data generation depending on external state?

Unexpected Protostar error. Report it here:
https://github.com/software-mansion/protostar/issues

Inconsistent data generation! Data generation behaved differently between different runs. Is your data generation depending on external state?

```

**Comment by mkaput** [comment]
Hey @JorikSchellekens! Thanks for reporting the bug. Unfortunately, Protostar didn't report the testing seed (I have created a separate issue for this #592), and I cannot reproduce this locally.

I submitted #594  with your snippet to our testing suite, and we will be observing the behaviour of this test case in our CI. Hopefully we'll be able to catch the offending code path 🤞🏻

**Comment by JorikSchellekens** [comment]
Works on my laptop, great work!
