### ISSUE TITLE
Unexpected Error when deploy server disconnects

### ISSUE THREAD

**Issue by Radinyn** [software-mansion/protostar#653]
## Protostar version
| Name       | Version              |
| ---------- | -------------------- |
| Protostar  | `0.3.2`  |
| Cairo-lang | `0.9.1` |
| Git        | `2.37.2`        |

## Current Behavior
After waiting for acceptance too long an exception is raised.

```
Unexpected Protostar error. Report it here:                                     
https://github.com/software-mansion/protostar/issues

Traceback (most recent call last):
  File "binary_entrypoint.py", line 85, in <module>
  File "binary_entrypoint.py", line 19, in init
  File "protostar/start.py", line 23, in main
  File "protostar/start.py", line 56, in run_protostar
  File "protostar/start.py", line 51, in run_protostar
  File "asyncio/runners.py", line 43, in run
  File "asyncio/base_events.py", line 587, in run_until_complete
  File "protostar/protostar_cli.py", line 60, in run
  File "protostar/protostar_cli.py", line 94, in _run_command_from_args
  File "protostar/cli/cli_app.py", line 28, in run
  File "protostar/commands/deploy/deploy_command.py", line 125, in run
  File "protostar/starknet_gateway/gateway_facade.py", line 125, in deploy
  File "starknet_py/net/client.py", line 151, in wait_for_tx
  File "starknet_py/net/gateway_client.py", line 212, in get_transaction_receipt
  File "starknet_py/net/http_client.py", line 69, in call
  File "starknet_py/net/http_client.py", line 41, in request
  File "starknet_py/net/http_client.py", line 54, in _make_request
  File "aiohttp/client.py", line 1138, in __aenter__
  File "aiohttp/client.py", line 559, in _request
  File "aiohttp/client_reqrep.py", line 898, in start
  File "aiohttp/streams.py", line 616, in read
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
[17671] Failed to execute script 'binary_entrypoint' due to unhandled exception!
```

## Expected Behavior
It should probably be wrapped in a ProtostarException.
It will still interfere with complex migration scripts that have to wait. (**!!!**)
Perhaps some other method of waiting is needed?

## Steps to Reproduce
1. `protostar deploy <path> --network alpha-goerli --wait-for-acceptance` (unreliable)

**Comment by DaveVodrazka** [comment]
Getting the same error after calling

```
protostar deploy [path-to-contract] --salt [salt] --gateway-url http://127.0.0.1:5050 --chain-id 23448594291968334
```

with `starknet-devnet` running via

```
sudo docker run -p 127.0.0.1:5050:5050 shardlabs/starknet-devnet --seed [seed]
```

**Comment by MaksymilianDemitraszek** [comment]
Probably not relevant anymore
