### ISSUE TITLE
Support different CPU architectures (ARM most importantly)

### ISSUE THREAD

**Issue by Arcticae** [software-mansion/protostar#90]
We need to support running this took natively on apple silicon which is becoming more common, so supporting other archs should not be that difficult

**Comment by Arcticae** [comment]
QEMU on GH can be used to accomplish it, there's an action which does exactly that:

https://github.com/uraimo/run-on-arch-action

**Comment by tarrencev** [comment]
this would be great to support for running protostar in arm64 dockers

**Comment by pmuens** [comment]
Just a quick update that I tried to run Protostar natively on my M1 MacBook Pro 14".

I build it from source following the steps outlined [here](https://docs.swmansion.com/protostar/docs/tutorials/installation) and get the following error when I run `protostar test`:

```sh
philipp@Philipps-MacBook-Pro-14> protostar test                                                                                                                                          ~/Downloads/test
12:20:51 [INFO] Collected 1 suite, and 2 test cases (0.034 s)                                                                                                                                                          
usage: protostar [-h] [--profile PROFILE] [--version] [--no-color] {init,build,install,remove,update,upgrade,test,deploy,declare} ...
usage: protostar [-h] [--profile PROFILE] [--version] [--no-color] {init,build,install,remove,update,upgrade,test,deploy,declare} ...
protostar: error: argument command: invalid choice: 'tracker_fd=9' (choose from 'init', 'build', 'install', 'remove', 'update', 'upgrade', 'test', 'deploy', 'declare')
protostar: error: argument command: invalid choice: 'from multiprocessing.resource_tracker import main;main(8)' (choose from 'init', 'build', 'install', 'remove', 'update', 'upgrade', 'test', 'deploy', 'declare')
Unexpected Protostar error. Report it here:
https://github.com/software-mansion/protostar/issues

Traceback (most recent call last):
  File "binary_entrypoint.py", line 11, in <module>
  File "protostar/start.py", line 33, in main
  File "protostar/start.py", line 28, in main
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 642, in run_until_complete
  File "protostar/protostar_cli.py", line 254, in run
  File "protostar/cli/cli_app.py", line 28, in run
  File "protostar/commands/test/test_command.py", line 108, in run
  File "protostar/commands/test/test_command.py", line 171, in test
  File "protostar/commands/test/test_scheduler.py", line 32, in run
  File "multiprocessing/context.py", line 57, in Manager
  File "multiprocessing/managers.py", line 557, in start
  File "multiprocessing/connection.py", line 255, in recv
  File "multiprocessing/connection.py", line 419, in _recv_bytes
  File "multiprocessing/connection.py", line 388, in _recv
EOFError
[14313] Failed to execute script 'binary_entrypoint' due to unhandled exception!
```

**Comment by Arcticae** [comment]
> Just a quick update that I tried to run Protostar natively on my M1 MacBook Pro 14".
> 
> I built it from source following the steps outlined [here](https://docs.swmansion.com/protostar/docs/tutorials/installation) and get the following error when I run `protostar test`:
> 
> ```shell
> philipp@Philipps-MacBook-Pro-14> protostar test                                                                                                                                          ~/Downloads/test
> 12:20:51 [INFO] Collected 1 suite, and 2 test cases (0.034 s)                                                                                                                                                          
> usage: protostar [-h] [--profile PROFILE] [--version] [--no-color] {init,build,install,remove,update,upgrade,test,deploy,declare} ...
> usage: protostar [-h] [--profile PROFILE] [--version] [--no-color] {init,build,install,remove,update,upgrade,test,deploy,declare} ...
> protostar: error: argument command: invalid choice: 'tracker_fd=9' (choose from 'init', 'build', 'install', 'remove', 'update', 'upgrade', 'test', 'deploy', 'declare')
> protostar: error: argument command: invalid choice: 'from multiprocessing.resource_tracker import main;main(8)' (choose from 'init', 'build', 'install', 'remove', 'update', 'upgrade', 'test', 'deploy', 'declare')
> Unexpected Protostar error. Report it here:
> https://github.com/software-mansion/protostar/issues
> 
> Traceback (most recent call last):
>   File "binary_entrypoint.py", line 11, in <module>
>   File "protostar/start.py", line 33, in main
>   File "protostar/start.py", line 28, in main
>   File "asyncio/runners.py", line 44, in run
>   File "asyncio/base_events.py", line 642, in run_until_complete
>   File "protostar/protostar_cli.py", line 254, in run
>   File "protostar/cli/cli_app.py", line 28, in run
>   File "protostar/commands/test/test_command.py", line 108, in run
>   File "protostar/commands/test/test_command.py", line 171, in test
>   File "protostar/commands/test/test_scheduler.py", line 32, in run
>   File "multiprocessing/context.py", line 57, in Manager
>   File "multiprocessing/managers.py", line 557, in start
>   File "multiprocessing/connection.py", line 255, in recv
>   File "multiprocessing/connection.py", line 419, in _recv_bytes
>   File "multiprocessing/connection.py", line 388, in _recv
> EOFError
> [14313] Failed to execute script 'binary_entrypoint' due to unhandled exception!
> ```

If you're on mac - you can use rosetta, so following instructions for installation will work for you (that's the way we use protostar over at SWM)

**Comment by pmuens** [comment]
@Arcticae thanks for the follow-up. I just tried it on my Intel Mac and ran into the exact same error (`ailed to execute script 'binary_entrypoint' due to unhandled exception!`).

What I did is:

1. Clone the repository
2. Build Protostar from source according to the [docs](https://docs.swmansion.com/protostar/docs/tutorials/installation)
3. Move the `protostar` directory to `~/Desktop`
4. Run `protostar init` to create a new project
5. `cd` into the project
6. Run `../protostar/protostar test`

**Comment by Arcticae** [comment]
> @Arcticae thanks for the follow-up. I just tried it on my Intel Mac and ran into the exact same error (`ailed to execute script 'binary_entrypoint' due to unhandled exception!`).
> 
> What I did is:
> 
> 1. Clone the repository
> 2. Build Protostar from source according to the [docs](https://docs.swmansion.com/protostar/docs/tutorials/installation)
> 3. Move the `protostar` directory to `~/Desktop`
> 4. Run `./protostar/protostar init` to create a new project
> 5. `cd` into the project
> 6. Run `../protostar/protostar test`
> 
> Python 3.9.6 Poetry version 1.1.10

I mean if you're only trying to use it, don't build it from source since it may be difficult. You can just do:

`curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash`

As listed in the instruction [here](https://github.com/software-mansion/protostar#installation)

**Comment by MaksymilianDemitraszek** [comment]
@Arcticae Is this one done?

**Comment by Arcticae** [comment]
@MaksymilianDemitraszek TBH no users reported lack of architecture support, i think we can close for now.
