### ISSUE TITLE
Protostar update doesn't work

### ISSUE THREAD

**Issue by iamreadyi** [software-mansion/protostar#908]
I can't update openzeppelin cairo_contracts.

Repo: https://github.com/iamreadyi/cairo-synthetic-staking-and-lottery

Error:

protostar update cairo_contracts
23:27:02 [INFO] Running dependency update                                                               
23:27:02 [ERROR] Update command failed
Unexpected Protostar error. Report it here:
https://github.com/software-mansion/protostar/issues

Traceback (most recent call last):
  File "git/util.py", line 1013, in __getitem__
  File "git/util.py", line 1001, in __getattr__
AttributeError: 'IterableList' object has no attribute 'cairo_contracts'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "git/repo/base.py", line 374, in submodule
  File "git/util.py", line 1015, in __getitem__
IndexError: No item found with id 'cairo_contracts'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "binary_entrypoint.py", line 88, in <module>
  File "binary_entrypoint.py", line 22, in init
  File "protostar/start.py", line 23, in main
  File "protostar/start.py", line 56, in run_protostar
  File "protostar/start.py", line 51, in run_protostar
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "protostar/protostar_cli.py", line 61, in run
  File "protostar/protostar_cli.py", line 97, in _run_command_from_args
  File "protostar/cli/cli_app.py", line 28, in run
  File "protostar/commands/update/update_command.py", line 66, in run
  File "protostar/commands/update/update_command.py", line 63, in run
  File "protostar/commands/update/update_command.py", line 77, in update
  File "protostar/commands/update/update_package.py", line 22, in update_package
  File "git/repo/base.py", line 376, in submodule
ValueError: Didn't find submodule named 'cairo_contracts'
[4390] Failed to execute script 'binary_entrypoint' due to unhandled exception!

**Comment by kasperski95** [comment]
Try removing and installing the package.

OpenZeppelin team recommends installing specific version of cairo-contracts (https://github.com/software-mansion/protostar/issues/902) e.g. `protostar install OpenZeppelin/cairo-contracts@v0.3.2`. We plan to deprecate/rework `protostar update`.
